version: "3.7"
services:

  api:
    build: 
      context: ./api
    container_name: api
    environment:
      - CONNECTION_STRING=postgres://postgres:postgres@db/postgresDB
    command: node index.js
    ports:
      - "3001:3001"
    networks:
      - Private_Network
      - Public_Network
    volumes:
      - ./api:/api
    depends_on:
      - db

  web:
    build: 
      context: ./web
    container_name: web
    environment:
      - API_URL=http://api:3001/data
    command: node index.js
    ports:
      - "80:3000"
    networks:
      - public
    volumes:
      - ./web:/web    
    depends_on:
      - api

  db:
    image: postgres:11.2-alpine
    ports: ["5432"]
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgresDB"
    networks:
      - private
    volumes:
      - "/home/ubuntu/english2arabic/sql_scripts/:/docker-entrypoint-initdb.d"  

networks:
  Public_Network:
    - driver: bridge
  Public_Network:
    - driver: bridge